### ISSUE TITLE
JsonSyntaxError after upgrading selenium-server-standalone to 3.13

### ISSUE THREAD

**Issue by jakubkierzkowski** [RationaleEmotions/talk2grid#2]
At the company I work for we've upgraded our grid's selenium-server-standalone from 3.11 to 3.13. And now we had to comment the line `Host node = assistant.getNodeDetailsForSession(sessionId);` out because of the following error:
```
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 2 path $
	at com.google.gson.JsonParser.parse(JsonParser.java:65)
	at com.google.gson.JsonParser.parse(JsonParser.java:45)
	at com.rationaleemotions.SimpleHttpClient.post(SimpleHttpClient.java:36)
	at com.rationaleemotions.GridApiAssistant.getNodeDetailsForSession(GridApiAssistant.java:47)
```
Now we cannot log the IP of the node used by a particular test.

**Comment by krmahadevan** [comment]
I will take a look at this and get back to you in a day. Thanks for
bringing this to my notice.

**Comment by krmahadevan** [comment]
@Jaahquubel - This is now fixed and published as part of v1.2.0. Please upgrade and try again.

**Comment by jakubkierzkowski** [comment]
It works. Thank you!

**Comment by krmahadevan** [comment]
Great. Stay tuned for the next release of this library. I found a whole
bunch of new things in the Grid for which I think I would now be able to
provide client side APIs. Just waiting for Selenium 3.14 to be released (I
am also pushing in a couple of new end-points to be queried via APIs in
this version. Fingers crossed :) )
